### ISSUE TITLE
Not working with Python3

### ISSUE THREAD

**Issue by NicolasWebDev** [jorvi/shiki#1]
Hi,

I am using archlinux, and the default python installation is python3.

So when running shiki, I have the following error:
```
: ~/shiki [master|✚ 1]$ shiki chien                                                                     
  File "<string>", line 1
    import urllib, sys; print urllib.quote(sys.argv[1])
                                   ^
SyntaxError: invalid syntax
```

When calling it explicitly with python2, it works fine.

I guess it is because of the print, without the parenthesis.
The best would be to have a syntax compatible between python 2 and python 3.

**Comment by jorvi** [comment]
Ah, good catch @NicolasWebDev!

I'll have a better look later in the week :) but explicitly calling python2 indeed seems like a nice stopgap.

**Comment by jorvi** [comment]
Apparently there have also been some changes to urllib from 2 -> 3, which would require specific workarounds. Its much easier and cleaner to just explicitly call `python2`, which will probably stick around for a very long time for legacy compatibility :)

**Comment by NicolasWebDev** [comment]
Thanks for the fix!

I did not know that python2 was a command present on every distro, I thought it was distro-dependent.
